name: 'ezoidc KV'
description: 'KV store'
inputs:
  org:
    description: 'org'
    required: true
  endpoint:
    description: 'endpoint'
    default: https://ts-xa2aecp7.golden-bull.ts.net
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Request OIDC Token
      id: oidc
      uses: actions/github-script@v6
      env: 
        ORG: ${{ inputs.org }}
        ENDPOINT: ${{ inputs.endpoint }}
      with:
        script: |
          const {ORG, ENDPOINT} = process.env;
          const audience = `https://oidc.bcj.io/${ORG}`;
          const token = await core.getIDToken(audience);
          const response = await fetch(ENDPOINT+"/api/v0/variables", {
            method: 'POST',
            headers: {'Authorization': `Bearer ${token}`, 'X-Ezoidc-Org': ORG}
          });
          const body = await response.json();
          
          if(!response.ok) {
            return core.setFailed(body);
          }
          
          for(let {key, sensitive, value, envvar} of body.variables) {
             if(sensitive) {
               core.setSecret(value);
             }

             core.exportVariable(envvar, value);

             core.info(`Set env ${envvar} to ${key} (sensitive=${sensitive})`);
          }
