name: 'ezoidc KV'
description: 'KV store'
inputs:
  org:
    description: 'org'
    required: true
  variables:
    description: 'variables JSON'
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - name: ezoidc
      uses: actions/github-script@v6
      env: 
        ORG: ${{ inputs.org }}
        SCRIPT_SRC: ${{ github.action_path }}/index.js
      with:
        script: |
          const { SCRIPT_SRC } = process.env;
          const action = require(SCRIPT_SRC);

          await action({github, context, core, fetch});
